// AUTOGENERATED_REMOVE_AFTER_CHANGES
#ifndef _HYDRA_NGINE_CORE_VIDEO_HPP
#define _HYDRA_NGINE_CORE_VIDEO_HPP
#include "core/assets.hpp"
#include "core/display.hpp"
namespace hydra {
    namespace video {
        class VideoInterface {
        private:
            /* data */
        protected:
            VideoInterface(void* prefs = nullptr){};

        public:
            virtual ~VideoInterface(){};
            virtual bool init(WindowInterface& window, std::list<base::Material*>& objects) = 0;
            virtual void draw(std::list<base::ManagedObject*>& objects) = 0;
        };
    }  // namespace video
}  // namespace hydra
#endif  //_HYDRA_NGINE_CORE_VIDEO_HPP
