//AUTOGENERATED_REMOVE_AFTER_CHANGES
#ifndef _HYDRA_NGINE_DRIVERS_OPENGL_HPP
#define _HYDRA_NGINE_DRIVERS_OPENGL_HPP
namespace hydra {
    namespace drivers {
        
    }
}

#endif //_HYDRA_NGINE_DRIVERS_OPENGL_HPP
